config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from wagtail.wagtailadmin import urls as wagtailadmin_urls
from wagtail.wagtaildocs import urls as wagtaildocs_urls
from wagtail.wagtailcore import urls as wagtail_urls

from search.views import search

BACKEND_NAME = 'Eraldo Energy backend'
admin.site.site_header = BACKEND_NAME
admin.site.site_title = BACKEND_NAME

urlpatterns = [
    # Meta information
    url(r'^robots\.txt/$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    url(r'^humans\.txt/$', TemplateView.as_view(template_name='humans.txt', content_type='text/plain')),
    # Django Admin, use {% url 'admin:index' %}
    url(r'^{}/'.format(settings.ADMIN_URL), include(admin.site.urls)),

    # url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name="home"),
    # url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),

    # User management
    url(r'^users/', include('eraldoenergy.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^dance/', include('dance.urls', namespace='dance')),
    url(r'^contact/', include('contact.urls', namespace='contact')),
    url(r'^items/', include('inventory.urls', namespace='inventory')),
    url(r'', include('pages.urls', namespace='pages')),

    # CMS wagtail
    url(r'^cms/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),
    url(r'^search/$', search, name='search'),  # optional

    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's serving mechanism
    url(r'', include(wagtail_urls)),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request),
        url(r'^403/$', default_views.permission_denied),
        url(r'^404/$', default_views.page_not_found),
        url(r'^500/$', default_views.server_error),
    ]

contact/urls.py
from django.conf.urls import url
from .views import ContactView, T42View

__author__ = 'eraldo'

urlpatterns = [
    # ex: ../contact/
    url(r'^$',
        ContactView.as_view(),
        name='home'),
    # ex: ../T42/
    url(r'^T42/$',
        T42View.as_view(),
        name='T42'),
]

dance/urls.py
from django.conf.urls import url
from .views import DanceView

__author__ = 'eraldo'

urlpatterns = [
    # ex: ../dance/
    url(r'^$',
        DanceView.as_view(),
        name='home'),
]

contact/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, HTML, Fieldset
from django import forms
from django.core.mail import send_mail

__author__ = 'Eraldo Energy'


class EmailField(Field):
    def render(self, *args, **kwargs):
        html = super(EmailField, self).render(*args, **kwargs)
        return html.replace('type="text"', 'type="email"', 1)


class ContactForm(forms.Form):
    email = forms.EmailField(label="email")
    message = forms.CharField(label="message", widget=forms.Textarea)

    def send_email(self):
        # send email using the self.cleaned_data dictionary

        email = self.cleaned_data["email"]
        message = self.cleaned_data["message"]

        # debug
        # print("should send email now to {} with message {}".format(email, message))

        # production
        subject = "[eraldo.org] message from '{}'".format(email)
        send_mail(subject, message, email, ['eraldo@eraldo.org'])

    helper = FormHelper()
    helper.form_action = '.'
    helper.html5_required = True
    helper.form_class = 'form-horizontal'
    helper.layout = Layout(
        Fieldset(
            'contact form',
            EmailField('email', css_class='form-control', placeholder="your email"),
            Field('message', rows="4", css_class='form-control', placeholder="your message", style="resize: vertical;"),
        ),
        HTML("""
        <br>
        <button type="submit" class="btn btn-lg btn-primary"><span class="glyphicon glyphicon-send"></span> send
            message
        </button>
         """),
    )

contact/views.py
from django.contrib import messages
from django.views.generic import FormView, TemplateView
from .forms import ContactForm

__author__ = "Eraldo Energy"


class ContactView(FormView):
    template_name = "contact/contact.html"
    form_class = ContactForm
    success_url = '.'

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        form.send_email()
        messages.success(self.request, 'Your message has been sent.')
        return super(ContactView, self).form_valid(form)


class T42View(TemplateView):
    template_name = "contact/T42.html"

contact/templates/contact/T42.html
{% extends 'base.html' %}

{% block title %}
    contact
{% endblock %}

{% block extrahead %}
{% endblock %}

{% block content_wrapper %}

    <div class="section section-stretch section-lightgray">

        {#    <div class="container">#}
        <h1 class="tagline"><i>tea for two</i></h1>
    </div>

    <div class="section-end section-end-lightgrey"></div>

    <div class="section section-lightgray" style="padding-top: 0px;">
        <div id="vcard" class="jumbotron">
            <div class="row" style="text-align: center">
                <div class="col-xs-12">
                    <a href="{% url 'contact:home' %}">
                        <img src="{{ STATIC_URL }}pages/images/T42.jpg"
                             class="img-circle img-responsive">
                    </a>
                </div>
                <div class="col-lg-12">
                    <h1>T42</h1>

                    <p>
                        A social project of mine. I schedule a private meeting with one
                        person every week.<br>
                        <br>
                        <i>How do I chose those people?</i><br>
                        By one of three ways:<br>
                    <ol>
                        <li>By picking people I want to get to know better.</li>
                        <li>By applications I get from people.</li>
                        <li>To stay in touch with people whom I have not seen for a while.</li>
                    </ol>
                    If you are interested in taking part..<br>
                    feel free to <a href="{% url 'contact:home' %}">contact me</a>.
                    </p>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block extra-script %}
    <script>
        $('#carousel-main').carousel()
    </script>
{% endblock %}

contact/templates/contact/contact.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    contact
{% endblock %}

{% block extrahead %}
{% endblock %}

{% block content_wrapper %}

    <div class="section section-stretch section-lightgray">

        {#    <div class="container">#}
        <h1 class="tagline">let us get in touch</h1>
    </div>

    <div class="section-end section-end-lightgrey"></div>

    <div class="section section-lightgray" style="padding-top: 0px;">
        <div id="vcard" class="jumbotron">
            <div class="row" style="text-align: center">
                <div class="col-lg-12">
                    <h1>Eraldo Energy</h1>

                    <p><span style="color: gray"><span
                            class="glyphicon glyphicon-phone"></span> mobile</span><br>
                        <a href="tel:004917697994480">
                        +49 176 97 99 44 80</a>
                    </p>

                    <p><a href="mailto:homepage@eraldo.org" target="_blank"><span style="color: gray"><span
                            class="glyphicon glyphicon-envelope"></span> email</span><br>
                        homepage@eraldo.org</a></p>

                    <p><a href="{% url 'contact:T42' %}"><span style="color: gray"><span
                            class="glyphicon glyphicon-user"></span> face to face</span><br>
                        project T42</a></p>
                </div>
                <div class="col-xs-6">
                    <a href="https://www.facebook.com/Eraldo" target="_blank">
                        <img src="{{ STATIC_URL }}pages/images/contact/facebook-icon.png"
                             class="img-circle img-responsive">

                        <h2>facebook</h2>
                    </a>
                </div>
                <div class="col-xs-6">

                    <a href="https://plus.google.com/u/0/102746258450496109858" target="_blank">
                        <img src="{{ STATIC_URL }}pages/images/contact/google-plus.png"
                             class="img-circle img-responsive">

                        <h2>google+</h2>
                    </a>
                </div>
            </div>
        </div>
        <div class="section-end section-end-e"></div>
    </div>
    <div class="section-end section-end-lightgrey"></div>


    <div class="section row">
        <div id="contact-form" class="col-lg-8 col-lg-offset-2">
            {% crispy form %}
        </div>
    </div>
    <div class="section-end section-end-white"></div>

    <div class="section section-grey">
        <div class="section-end section-end-grey"></div>
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d310839.14558408665!2d13.425136449999998!3d52.50754189999999!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47a84e373f035901%3A0x42120465b5e3b70!2sBerlin%2C+Germany!5e0!3m2!1sen!2sus!4v1438685023835" width="100%" height="480" frameborder="0" style="border:0" allowfullscreen></iframe>
    </div>
    {#    <div class="section-end section-end-grey"></div>#}

{% endblock %}

{% block extra-script %}
    <script>
        $('#carousel-main').carousel()
    </script>
{% endblock %}