config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from wagtail.wagtailadmin import urls as wagtailadmin_urls
from wagtail.wagtaildocs import urls as wagtaildocs_urls
from wagtail.wagtailcore import urls as wagtail_urls

from search.views import search

BACKEND_NAME = 'Eraldo Energy backend'
admin.site.site_header = BACKEND_NAME
admin.site.site_title = BACKEND_NAME

urlpatterns = [
    # Meta information
    url(r'^robots\.txt/$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    url(r'^humans\.txt/$', TemplateView.as_view(template_name='humans.txt', content_type='text/plain')),
    # Django Admin, use {% url 'admin:index' %}
    url(r'^{}/'.format(settings.ADMIN_URL), include(admin.site.urls)),

    # url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name="home"),
    # url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),

    # User management
    url(r'^users/', include('eraldoenergy.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^dance/', include('dance.urls', namespace='dance')),
    url(r'^contact/', include('contact.urls', namespace='contact')),
    url(r'^items/', include('inventory.urls', namespace='inventory')),
    url(r'', include('pages.urls', namespace='pages')),

    # CMS wagtail
    url(r'^cms/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),
    url(r'^search/$', search, name='search'),  # optional

    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's serving mechanism
    url(r'', include(wagtail_urls)),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request),
        url(r'^403/$', default_views.permission_denied),
        url(r'^404/$', default_views.page_not_found),
        url(r'^500/$', default_views.server_error),
    ]

dance/urls.py
from django.conf.urls import url
from .views import DanceView

__author__ = 'eraldo'

urlpatterns = [
    # ex: ../dance/
    url(r'^$',
        DanceView.as_view(),
        name='home'),
]

eraldoenergy/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

eraldoenergy/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_("Name of User"), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

eraldoenergy/dance/views.py
from django.db.models import Q
from django.views.generic import TemplateView
from .models import Instructor, Group
from eraldoenergy.events.models import Event


class DanceView(TemplateView):
    template_name = "dance/dance.html"

    def get_context_data(self, **kwargs):
        context = super(DanceView, self).get_context_data(**kwargs)
        context['events'] = Event.objects.filter(type__startswith='dance')
        context['show_events'] = Event.objects.filter(type__exact="dance show")
        context['instructors'] = Instructor.objects.filter(Q(gender__exact='M') | Q(partner__isnull=True)).distinct()
        context['groups'] = Group.objects.all()
        return context

eraldoenergy/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from braces.views import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

eraldoenergy/templates/base.html
{% load staticfiles i18n %}
{% load static wagtailuserbar wagtailcore_tags wagtailimages_tags %}
<!DOCTYPE html>
<html lang="en" ng-app>
<!--
01000101 01110010 01100001 01101100 01100100 01101111

8888888888                 888      888             Very nice.. so you do read code. :D
888                        888      888
888                        888      888             Like my site? => contact me
8888888    888d888 8888b.  888  .d88888  .d88b.     Hate my site? => contact me
888        888P"      "88b 888 d88" 888 d88""88b
888        888    .d888888 888 888  888 888  888    Not sure yet? => keep looking :P
888        888    888  888 888 Y88b 888 Y88..88P
8888888888 888    "Y888888 888  "Y88888  "Y88P"   .org

01000101 01110010 01100001 01101100 01100100 01101111
-->

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>
        {% block title %}{% if self.seo_title %}{{ self.seo_title }}{% else %}{{ self.title }}{% endif %}{% endblock %}
        {% block title_suffix %}{% endblock %}</title>
    {#    <title>{% block title %}Eraldo Energy{% endblock title %}</title>#}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Eraldo Energy website">
    <meta name="author" content="Eraldo Energy">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    {# favicon #}
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">

    <link rel="author" href="https://plus.google.com/https://plus.google.com/102746258450496109858?rel=author"/>

    <link rel="canonical" href="http://eraldo.org/"/>
    <meta property='og:locale' content='en_US'/>
    <meta property='og:type' content='website'/>
    <meta property='og:title' content='Eraldo Energy - Person'/>
    <meta property='og:url' content='http://eraldo.org/'/>
    <meta property='og:site_name' content='eraldo.org - Eraldo Energy'/>
    <meta property="og:image" content="{% static 'images/Avatar.jpg' %}"/>
    <meta property="og:description"
          content="Want to get in touch with or inform yourself about Eraldo Energy? You&#x27;re in the right place."/>

    <meta name="author" content="Eraldo Energy">
    <meta name="description"
          content="Want to get in touch with or inform yourself about Eraldo Energy? You&#x27;re in the right place."/>
    <meta itemprop='image' content='{% static 'images/Avatar.jpg' %}'>
    <meta http-equiv='Content-Type' content='text/html; charset=utf-8'>


    {% block css %}
        <!-- Latest compiled and minified CSS -->
        {# TODO: update to new bootstrap #}
        {#        <link rel="stylesheet" href="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css">#}
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

        {# TODO: update older to css block? #}
        {% block extrahead %}{% endblock %}

        <!-- Your stuff: Third-party css libraries go here -->

        <!-- This file store project specific CSS -->
        <link href="{% static 'css/project.css' %}" rel="stylesheet">
        <link href="{% static 'pages/css/pages.css' %}" rel="stylesheet">
        {#        <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}pages/css/base.css"/>#}
    {% endblock %}

{#    {% block angular %}#}
{#        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.4/angular.min.js"></script>#}
{#    {% endblock %}#}

    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
      (adsbygoogle = window.adsbygoogle || []).push({
        google_ad_client: "ca-pub-5497492448845482",
        enable_page_level_ads: true
      });
    </script>

</head>

<body data-spy="scroll" data-target="#main-menu">
{% wagtailuserbar %}
<div id="wrap">

    <div class="container">

        <div id="main-menu" class="navbar navbar-default navbar-fixed-top" role="navigation" data-spy="affix"
             data-offset-top="20">
            <div class="container">

                <div class="row" style="text-align: center; height: 100%;">

                    <div class="menu-bar menu-bar-left col-xs-4">
                        <a class="btn menu-btn visible-xs" href="javascript:;" data-toggle="collapse"
                           data-target=".navbar-collapse" onclick="$('.menu-btn').toggleClass('menu-btn-close');"></a>

                        <div class="navbar-collapse collapse">
                            <ul class="nav navbar-nav">
                                {#                                <li class="menu-link icon-link"><a href="{% url 'contact:home' %}">home</a></li>#}
                                <li class="menu-link"><a href="{% slugurl 'home' %}">about</a></li>
                                <li class="menu-link hidden-md hidden-lg"><a href="{% slugurl 'topics' %}">topics</a></li>
                                <li class="menu-link dropdown hidden-xs hidden-sm">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">topics <b
                                            class="caret"></b></a>
                                    <ul class="dropdown-menu pull-left text-left">
                                        <li><a href="{% url 'dance:home' %}">Dance</a></li>
                                        <li><a href="{% url 'pages:personal-development' %}">Personal Development</a>
                                        </li>
{#                                        <li><a href="{% url 'pages:web-design' %}">Web Design</a></li>#}
                                        <li><a href="{% url 'pages:technology' %}">Technology</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>

                    <div class="menu-bar menu-bar-center col-xs-4">
                            <div class="logo-img">
                                <a href="{% url 'contact:home' %}">
                                    <img class="img-circle img-responsive"
                                         src="{% static 'images/Avatar.jpg' %}">
                                </a>
                            </div>
                            <div class="logo-bar">
                                <a class="logo-text" href="{% url 'contact:home' %}" title="Home">eraldo</a>
                            </div>
                            <div class="call-bar navbar-collapse collapse">
                                <a class="btn btn-lg call-btn visible-xs" href="tel:004917697994480"
                                   title="call Eraldo"></a>
                            </div>
                    </div>

                    <div class="menu-bar menu-bar-right col-xs-4">
                        <a class="btn menu-btn visible-xs" href="javascript:;" data-toggle="collapse"
                           data-target=".navbar-collapse" onclick="$('.menu-btn').toggleClass('menu-btn-close');"></a>

                        <div class="navbar-collapse collapse">
                            <ul id="blog-container" class="nav navbar-nav">
                                {% if user.is_authenticated %}
                                    <li class="menu-link"><a href="{% slugurl 'blog' %}">blog</a></li>
                                {% else %}
                                    <li class="menu-link" data-toggle="tooltip" data-placement="bottom" title="Only for registered users.">
                                        <a href="#blog">blog</a>
                                    </li>
                                {% endif %}
                                <li class="menu-link"><a href="{% url 'contact:home' %}">contact</a></li>
                            </ul>
                        </div>
                    </div>

                </div>
                <div class="dongle"></div>
            </div>

        </div>
    </div>


    <div id="content" class="container">
        <div class="dongle"></div>

        {% if messages %}
            <div id="messages" class="section section-lightgray">
                {% for message in messages %}
                    <div class="alert alert-dismissable{% if message.tags %} alert-{{ message.tags }}{% endif %}">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        {% endif %}

        {% block content_wrapper %}

            <div class="section section-stretch section-lightgray">

                <h1 class="tagline"><i>{% if page %}{{ page.title }}{% elif title %}{{ title }}{% endif %}</i></h1>
            </div>

            <div class="section-end section-end-lightgrey"></div>

            <div class="section section-lightgray" style="padding-top: 0px;">
                <div id="vcard" class="jumbotron">
                    <div class="row" style="text-align: center">
                        <div class="col-xs-12">
                            {% if page.image %}
                                {% image page.image width-400 %}
                            {% endif %}
                        </div>
                        <div class="col-lg-12">
                            {% block content %}
                            {% endblock %}
                        </div>
                    </div>
                </div>
            </div>
        {% endblock %}
        <div id="content-footer" class="section section-lightgray text-center text-muted"
             style="padding-top: 8px;padding-bottom: 8px;">
            <p>This page has been visited 42,148,917 times since last Tuesday afternoon
                (estimated).
                <br>
                © {% now "Y" %} Eraldo Energy | <a href="{% url 'contact:home' %}">www.eraldo.org</a> | <a
                        href="{% url 'contact:home' %}">impressum</a> | <a href="{% url 'contact:home' %}">sitemap</a>
                | <a href="{% url 'contact:home' %}">Designed by Eraldo Webdesign</a>
            </p>
        </div>
    </div>
</div>


{# CONTAINER END #}


{% block modal %}{% endblock modal %}

</div>

<div id="footer" class="navbar navbar-inverse navbar-fixed-bottom">
    <div class="dongle dongle-bottom"></div>
    <div class="container" style="padding-top: 0px;">
        <div class="footer-bar footer-bar-left col-xs-3 col-sm-4">
            <a href="{% url 'pages:web-design' %}" class="text-muted credit hidden-xs">© 2013-{% now "Y" %} Eraldo Webdesign</a>
            <a href="{% url 'pages:web-design' %}" class="text-muted credit visible-xs">©</a>
        </div>
        <div class="footer-bar footer-bar-middle logo-bar col-xs-6 col-sm-4">
            <div class="social-bar">
                <a class="social social-facebook" href="https://www.facebook.com/Eraldo" target="_blank"></a>
                <a class="social social-google" href="https://plus.google.com/u/0/102746258450496109858"
                   target="_blank"></a>
            </div>
            <div class="logo-text-bar">
                <a class="logo-text" href="#">eraldo</a>
            </div>
        </div>
        <div class="footer-bar footer-bar-right col-xs-3 col-sm-4">
            <a href="{% url 'contact:home' %}" class="text-muted credit hidden-xs">✉ Contact Eraldo Energy</a>
            <a href="#" class="text-muted credit visible-xs">✉</a>
        </div>
    </div>
</div>

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
{% block javascript %}
    <!-- Latest JQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

    {# bootstrap #}
    <!-- Latest compiled and minified JavaScript -->
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    {#    <script src="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.js"></script>#}

    <!-- Your stuff: Third-party javascript libraries go here -->

    <!-- place project specific Javascript in this file -->
    <script src="{% static 'js/project.js' %}"></script>

    <script>
        {# determine the active selection in the menu #}
        {#   e.g.: #}
        {#   path: web/pages/something/?parameter #}
        {#   will detect "something" and add css class active to the links list element. #}
        $('#main-menu a[href*="' + location.pathname.split("/")[location.pathname.split("/").length - 2] + '"][class!="noselect"]').parent("li").addClass('active');
    </script>
    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
    </script>

    {% block extra-script %}{% endblock %}

{% endblock javascript %}
</body>
</html>